### ISSUE TITLE
Specifying only one object id in a query fails

### ISSUE THREAD

**Issue by jkerr5** [FeatureServer/FeatureServer#15]
When using the `objectIds` query field, if only one id is specified, an error is returned from koop.

When this url is passed in
```
FeatureServer/0/query?objectIds=1
```
this error is returned
```js
{"error":"oids.map is not a function"}
```
It looks like it's not parsing the object ids to an array if there is just one value.

**Comment by dmfenton** [comment]
Resolved @v2.3.1

**Comment by jkerr5** [comment]
The behavior is different now but it doesn't seem like using the `objectIds` query parameter is working correctly.

When specifying an `objectIds` query parameter, even though the provider is returning results, none of them appear in the results coming out of koop.

It may be related to another change in behavior with 2.3.1 which is that the `OBJECTID` fields are being stripped out of the results. Let me know if you want a separate issue for this but, even if I explicitly request the `OBJECTID` field using the `outFields` parameter, they do not appear in the results coming out of koop.

**Comment by tomtom92** [comment]
Can you check and make sure that this issue occurs after updating

**Comment by jkerr5** [comment]
Running 2.3.2, I see the following: 

Request URL: `/marklogic/GDeltGKG/FeatureServer/0/query?f=json&objectIds=1,8`

Provider response (note that there are two the two features requested):
```js
{
  "type": "FeatureCollection",
  "metadata": {
    "name": "GDeltGKG",
    "fields": [
      {
        "name": "OBJECTID",
        "type": "Integer"
      },
      {
        "name": "urlpubtimedate",
        "type": "Date"
      },
      {
        "name": "url",
        "type": "String"
      },
      {
        "name": "name",
        "type": "String"
      },
      {
        "name": "urltone",
        "type": "Double"
      },
      {
        "name": "domain",
        "type": "String"
      },
      {
        "name": "urllangcode",
        "type": "String"
      },
      {
        "name": "geores",
        "type": "Integer"
      }
    ]
  },
  "filtersApplied": {
    "geometry": true,
    "where": true
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 1,
        "urlpubtimedate": "2017-05-24T06:00:00Z",
        "url": "https:\/\/www.rtbf.be\/info\/monde\/detail_le-suspect-de-manchester-un-etudiant-reserve-issu-d-un-quartier-modeste?id=9615589",
        "name": "United Kingdom",
        "urltone": -3.41,
        "domain": "rtbf.be",
        "urllangcode": "fra",
        "geores": 1
      }
    },
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 8,
        "urlpubtimedate": "2017-05-24T06:00:00Z",
        "url": "https:\/\/www.rtbf.be\/info\/monde\/detail_le-suspect-de-manchester-un-etudiant-reserve-issu-d-un-quartier-modeste?id=9615589",
        "name": "Libya",
        "urltone": -3.41,
        "domain": "rtbf.be",
        "urllangcode": "fra",
        "geores": 1
      }
    }
  ]
}
```

This is the response from koop (note that it seems to have dropped the first feature and given the other feature an OBJECTID of 1
```js
{
  "objectIdFieldName": "OBJECTID",
  "globalIdFieldName": "",
  "hasZ": false,
  "hasM": false,
  "spatialReference": {
    "wkid": 4326
  },
  "fields": [
    {
      "name": "OBJECTID",
      "type": "esriFieldTypeInteger",
      "alias": "OBJECTID",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urlpubtimedate",
      "type": "esriFieldTypeDate",
      "alias": "urlpubtimedate",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "url",
      "type": "esriFieldTypeString",
      "alias": "url",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "name",
      "type": "esriFieldTypeString",
      "alias": "name",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urltone",
      "type": "esriFieldTypeDouble",
      "alias": "urltone",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "domain",
      "type": "esriFieldTypeString",
      "alias": "domain",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urllangcode",
      "type": "esriFieldTypeString",
      "alias": "urllangcode",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "geores",
      "type": "esriFieldTypeInteger",
      "alias": "geores",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    }
  ],
  "features": [
    {
      "type": "Feature",
      "attributes": {
        "OBJECTID": 1,
        "urlpubtimedate": 1495605600000,
        "url": "https:\/\/www.rtbf.be\/info\/monde\/detail_le-suspect-de-manchester-un-etudiant-reserve-issu-d-un-quartier-modeste?id=9615589",
        "name": "Libya",
        "urltone": -3.41,
        "domain": "rtbf.be",
        "urllangcode": "fra",
        "geores": 1
      }
    }
  ]
}
```
I believe that the OBJECTID field is being stripped out at some point. Here is an additional example:

URL: `/marklogic/GDeltGKG/FeatureServer/0/query?f=json&resultRecordCount=1`

This returns one feature from MarkLogic (note that it is OBJECTID 46099)
```js
{
  "type": "FeatureCollection",
  "metadata": {
    "name": "GDeltGKG",
    "fields": [
      {
        "name": "OBJECTID",
        "type": "Integer"
      },
      {
        "name": "urlpubtimedate",
        "type": "Date"
      },
      {
        "name": "url",
        "type": "String"
      },
      {
        "name": "name",
        "type": "String"
      },
      {
        "name": "urltone",
        "type": "Double"
      },
      {
        "name": "domain",
        "type": "String"
      },
      {
        "name": "urllangcode",
        "type": "String"
      },
      {
        "name": "geores",
        "type": "Integer"
      }
    ]
  },
  "filtersApplied": {
    "geometry": true,
    "where": true
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 46099,
        "urlpubtimedate": "2017-05-24T11:30:00Z",
        "url": "http:\/\/www.mathrubhumi.com\/news\/india\/pakistan-fighter-jets-fly-close-to-siachen-glacier--1.1961754",
        "name": "Pakistan",
        "urltone": 3.08,
        "domain": "mathrubhumi.com",
        "urllangcode": "mal",
        "geores": 1
      }
    }
  ]
}
```
This is the response from koop (note that the OBJECTID is now 0)
```js
{
  "objectIdFieldName": "OBJECTID",
  "globalIdFieldName": "",
  "hasZ": false,
  "hasM": false,
  "spatialReference": {
    "wkid": 4326
  },
  "fields": [
    {
      "name": "OBJECTID",
      "type": "esriFieldTypeInteger",
      "alias": "OBJECTID",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urlpubtimedate",
      "type": "esriFieldTypeDate",
      "alias": "urlpubtimedate",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "url",
      "type": "esriFieldTypeString",
      "alias": "url",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "name",
      "type": "esriFieldTypeString",
      "alias": "name",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urltone",
      "type": "esriFieldTypeDouble",
      "alias": "urltone",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "domain",
      "type": "esriFieldTypeString",
      "alias": "domain",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "urllangcode",
      "type": "esriFieldTypeString",
      "alias": "urllangcode",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    },
    {
      "name": "geores",
      "type": "esriFieldTypeInteger",
      "alias": "geores",
      "length": null,
      "editable": false,
      "nullable": true,
      "domain": null
    }
  ],
  "features": [
    {
      "type": "Feature",
      "attributes": {
        "OBJECTID": 0,
        "urlpubtimedate": 1495625400000,
        "url": "http:\/\/www.mathrubhumi.com\/news\/india\/pakistan-fighter-jets-fly-close-to-siachen-glacier--1.1961754",
        "name": "Pakistan",
        "urltone": 3.08,
        "domain": "mathrubhumi.com",
        "urllangcode": "mal",
        "geores": 1
      }
    }
  ]
}
```

Is there an additional `filtersApplied` property I should be setting?

**Comment by dmfenton** [comment]
No, this is a bug on our side. @tomtom92 will take this on. We'll get a fix out today or Monday.

**Comment by dmfenton** [comment]
@tomtom92 I think we need to automatically set `metadata.idField = 'OBJECTID'` if that field exists in the data.

**Comment by dmfenton** [comment]
@jkerr5 you can work around this by setting `metadata.idField = 'OBJECTID'` at the provider level.

**Comment by jkerr5** [comment]
Ah, yeah, I can do that. Are there any other fields from the layer descriptor metadata that I should also include in the query response metadata? I'll set these for now:
```js
    "idField": "OBJECTID",
    "displayField": "name",
```

**Comment by jkerr5** [comment]
Setting the `idField` fixes the calls for URL: `/marklogic/GDeltGKG/FeatureServer/0/query?f=json&resultRecordCount=1` but calls that use the `objectIds` parameter fail with this error:

```js
{"error":"oids.includes is not a function"}
```
This is the provider response now that produces this error:
```js
{
  "type": "FeatureCollection",
  "metadata": {
    "name": "GDeltGKG",
    "fields": [
      {
        "name": "OBJECTID",
        "type": "Integer"
      },
      {
        "name": "urlpubtimedate",
        "type": "Date"
      },
      {
        "name": "url",
        "type": "String"
      },
      {
        "name": "name",
        "type": "String"
      },
      {
        "name": "urltone",
        "type": "Double"
      },
      {
        "name": "domain",
        "type": "String"
      },
      {
        "name": "urllangcode",
        "type": "String"
      },
      {
        "name": "geores",
        "type": "Integer"
      }
    ],
    "idField": "OBJECTID",
    "displayField": "name"
  },
  "filtersApplied": {
    "geometry": true,
    "where": true
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 1,
        "urlpubtimedate": "2017-05-24T06:00:00Z",
        "url": "https:\/\/www.rtbf.be\/info\/monde\/detail_le-suspect-de-manchester-un-etudiant-reserve-issu-d-un-quartier-modeste?id=9615589",
        "name": "United Kingdom",
        "urltone": -3.41,
        "domain": "rtbf.be",
        "urllangcode": "fra",
        "geores": 1
      }
    },
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 8,
        "urlpubtimedate": "2017-05-24T06:00:00Z",
        "url": "https:\/\/www.rtbf.be\/info\/monde\/detail_le-suspect-de-manchester-un-etudiant-reserve-issu-d-un-quartier-modeste?id=9615589",
        "name": "Libya",
        "urltone": -3.41,
        "domain": "rtbf.be",
        "urllangcode": "fra",
        "geores": 1
      }
    }
  ]
}
```

**Comment by tomtom92** [comment]
@jkerr5, the first issue (when querying field objectIds with only one value) should be fixed. Let me know if you reproduce the error again. I will take a look at this new issue (calls using the objectIds field will fail) today.

**Comment by jkerr5** [comment]
I get a different error now but a single objectId still does not work. When I make a request with a URL like this that includes only one objectId
```
/marklogic/restaurants/FeatureServer/0/query?objectIds=1
```
my provider responds with this
```js
{
  "type": "FeatureCollection",
  "metadata": {
    "name": "restaurants",
    "fields": [
      {
        "name": "OBJECTID",
        "type": "Integer"
      },
      {
        "name": "Facility_N",
        "type": "String"
      },
      {
        "name": "Facility_I",
        "type": "String"
      },
      {
        "name": "Address",
        "type": "String"
      },
      {
        "name": "City",
        "type": "String"
      },
      {
        "name": "Zip",
        "type": "String"
      },
      {
        "name": "Latitude",
        "type": "Double"
      },
      {
        "name": "Longitude",
        "type": "Double"
      },
      {
        "name": "Inspection",
        "type": "Date"
      },
      {
        "name": "Related_ID",
        "type": "String"
      },
      {
        "name": "Score",
        "type": "Double"
      }
    ],
    "idField": "OBJECTID",
    "displayField": "Facility_N"
  },
  "filtersApplied": {
    "geometry": true,
    "where": true
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "OBJECTID": 1,
        "Facility_N": "ROUND TABLE PIZZA",
        "Facility_I": "FA0016195",
        "Address": "14898 DALE EVANS",
        "City": "APPLE VALLEY",
        "Zip": "92307",
        "Latitude": 34.525655,
        "Longitude": -117.215373,
        "Inspection": "2017-02-28-04:00",
        "Related_ID": "PR0021541",
        "Score": 94
      }
    }
  ]
}
```
and koop responds with this
```js
{"error":"oids.includes is not a function"}
```

**Comment by dmfenton** [comment]
Which version of node are you running?

**Comment by dmfenton** [comment]
Please test with with FeatureServer@2.3.3

**Comment by jkerr5** [comment]
Looks good on my side.

**Comment by tomtom92** [comment]
@jkerr5, sounds good. Let us know if these issues happen again.
